# Generated by Django 4.2.6 on 2023-10-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
    ]
