# Generated by Django 4.2.6 on 2023-10-10 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0002_remove_employee_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='ems_app.department'),
        ),
    ]
